WrapperOwningHolder.h does not exist on CMSSW_8_0
Found a another bug fix for Event_hacked but I fix it up to re-write
for CMSSW_8_0_X:

/afs/cern.ch/work/s/sfonseca/PPS/CT-PPSTOTEM_CMSSW_7_5_X/testing_raw_dat
a_files/CMSSW_8_0_0_pre5/src/TotemRawDataLibrary/Readers/plugins/Event_h
acked.h:28:62: fatal error:
DataFormats/Common/interface/WrapperOwningHolder.h: No such file or
directory
 #include "DataFormats/Common/interface/WrapperOwningHolder.h"
                                                              ^
compilation terminated.
In file included from
/afs/cern.ch/work/s/sfonseca/PPS/CT-PPSTOTEM_CMSSW_7_5_X/testing_raw_dat
a_files/CMSSW_8_0_0_pre5/src/TotemRawDataLibrary/Readers/plugins/RawData
Source.cc:10:0:
/afs/cern.ch/work/s/sfonseca/PPS/CT-PPSTOTEM_CMSSW_7_5_X/testing_raw_dat
a_files/CMSSW_8_0_0_pre5/src/TotemRawDataLibrary/Readers/plugins/Event_h
acked.h:28:62: fatal error:
DataFormats/Common/interface/WrapperOwningHolder.h: No such file or
directory
 #include "DataFormats/Common/interface/WrapperOwningHolder.h"

I